sharedEnvironments: &sharedEnvironments
  APPLICATION_ENVIRONMENT: "infura"
  SPRING_PROFILES_ACTIVE: '{{ include "service.env" $ }}'
  SPRING_CLOUD_CONSUL_ENABLED: false
  RARIBLE_CORE_APM_AGENT_ENABLED: false
  RARIBLE_CORE_CLIENT_K8S: true
  SPRING_DATA_ELASTICSEARCH_CLUSTERNAME: "docker-cluster"
  SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_MAXINMEMORYSIZE: 4194304
  SPRING_R2DBC_URL: "r2dbc:postgres://infura:infura@localhost:5432/test"
  INTEGRATION_ETHEREUM_AUCTIONCONTRACTS: "0x415a59308893c97b25755dF94f87A61066B9C53C"
  INTEGRATION_ETHEREUM_ENABLED: true
  INTEGRATION_POLYGON_ENABLED: false
  INTEGRATION_FLOW_ENABLED: false
  INTEGRATION_TEZOS_ENABLED: false
  INTEGRATION_SOLANA_ENABLED: false
  INTEGRATION_IMMUTABLEX_ENABLED: false
  SPRING_DATA_MONGODB_DATABASE: protocol-union

sharedTolerations: &sharedTolerations
  effect: NoSchedule
  key: env
  operator: Equal
  value: infura

protocol-union-api:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments

protocol-union-listener:
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    LISTENER_CONSUMER_BLOCKCHAINWORKERS_ETHEREUM: 24
    INTEGRATION_ETHEREUM_CONSUMER_WORKERS_OWNERSHIP: 8
  resources:
    jvm:
      xmx_megabytes: 2048
      max_direct_memory_megabytes: 1024

protocol-union-meta-loader:
  replicas: 12
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    RARIBLE_LOADER_LOADTASKSBATCHSIZE: 128
    RARIBLE_LOADER_WORKERS: 64
    RARIBLE_LOADER_LOADTASKSSERVICEINSTANCES: 12
    RARIBLE_LOADER_LOADTASKSTOPICPARTITIONS: 48
  resources:
    jvm:
      max_direct_memory_megabytes: 512

protocol-union-indexer:
  enabled: false
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments

protocol-union-worker:
  enabled: false
  tolerations:
    - *sharedTolerations
  environments:
    <<: *sharedEnvironments
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_0_BLOCKCHAIN: "ETHEREUM"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_0_ENABLED: false
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_1_BLOCKCHAIN: "POLYGON"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_1_ENABLED: false
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_2_BLOCKCHAIN: "FLOW"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_2_ENABLED: false
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_3_BLOCKCHAIN: "TEZOS"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_3_ENABLED: false
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_4_BLOCKCHAIN: "SOLANA"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_4_ENABLED: false
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_5_BLOCKCHAIN: "IMMUTABLEX"
    WORKER_REINDEXER_ACTIVITY_BLOCKCHAINS_5_ENABLED: false
