spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ${elasticsearch.cluster-nodes}

      client:
        reactive:
          endpoints:  ${elasticsearch.api-nodes}
          max-in-memory-size: 4194304

  elasticsearch:
    rest:
      uris: ${elasticsearch.api-nodes}