spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}
  config:
    use-legacy-processing: true
    import: "consul:"
  cloud:
    bootstrap:
      enabled: true

    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ${elasticsearch.cluster-nodes}

      client:
        reactive:
          endpoints:  ${elasticsearch.api-nodes}

  elasticsearch:
    rest:
      uris: ${elasticsearch.api-nodes}

redisUri: ${consul.redis.uri}