spring:
  data:
    mongodb:
      uri: mongodb://${mongodb.hosts}
      database: ${mongodb.database}

    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: ${elasticsearch.cluster-nodes}

      client:
        reactive:
          endpoints: ${elasticsearch.api-nodes}
          max-in-memory-size: 4194304

  config:
    use-legacy-processing: true
    import: "consul:"
  cloud:
    bootstrap:
      enabled: true
  elasticsearch:
    rest:
      uris: ${elasticsearch.api-nodes}

protocol:
  union:
    subscriber:
      broker-replica-set: ${kafka.hosts}
  aptos:
    subscriber:
      broker-replica-set: ${kafka.hosts}

redisUri: ${consul.redis.uri}
